server:
  port: 9595

spring:
  application:
    name: employee-service-flux

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/


info:
  name: Employee Services
  category: Red