server:
  port: 9696

spring:
  application:
    name: department-service-flux

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
info:
  name: Department Services
  category: Orange
