server:
  port: 8061
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


---
spring:
  config:
    activate:
      on-profile: local-p330-single,local-p330-cluster

server:
  ssl:
    enabled: true
    key-store: d:\ssl_certificates\server.jks
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost
eureka:
  instance:
    hostname: rixp330
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://rixp330:8061/eureka/, https://rixm1mini:8061/eureka/, https://rixmbp:8061/eureka/

---
spring:
  config:
    activate:
      on-profile: local-m1mac-single,local-m1mac-cluster

server:
  ssl:
    enabled: true
    key-store: /tmp/server.jks
    key-store-type: PKCS12
    key-store-password: localhost
    key-alias: localhost

eureka:
  instance:
    hostname: rixm1mini
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://rixp330:8061/eureka/, https://rixm1mini:8061/eureka/, https://rixmbp:8061/eureka/

---
spring:
  config:
    activate:
      on-profile: local-mbp-single,local-mbp-cluster

server:
  ssl:
    enabled: true
    key-store: /tmp/server.jks
    key-store-type: PKCS12
    key-store-password: localhost
    key-alias: localhost

eureka:
  instance:
    hostname: rixmbp
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://rixp330:8061/eureka/, https://rixm1mini:8061/eureka/, https://rixmbp:8061/eureka/
