server:
  port: 8061
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


---
spring:
  config:
    activate:
      on-profile: local-p330-single,local-p330-cluster

server:
  ssl:
    enabled: true
    key-store: d:\ssl_certificates\server.jks
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost


---
spring:
  config:
    activate:
      on-profile: local-mac-single,local-mac-cluster

server:
  ssl:
    enabled: true
    key-store: /tmp/server.jks
    key-store-type: PKCS12
    key-store-password: localhost
    key-alias: localhost
