server:
  port: 8061
  tomcat:
    accesslog:
      enabled: true
      buffered: false
      directory: D:\app_logs\eureka-server\access_logs
      max-days: 30
      prefix: eureka_access
      request-attributes-enabled: true
      rename-on-rotate: true
      

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring: # To resolve bug when multiple network interfaces are present https://github.com/spring-cloud/spring-cloud-commons/blob/main/docs/src/main/asciidoc/spring-cloud-commons.adoc#ignore-network-interfaces
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
        - 10.0

---
spring:
  config:
    activate:
      on-profile: local-p330-single

server:
  ssl:
    enabled: true
    key-store: d:\ssl_certificates\server.jks
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost
eureka:
  instance:
    hostname: rixp330
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://rixp330:8061/eureka/
---
spring:
  config:
    activate:
      on-profile: local-p330-cluster
server:
  ssl:
    enabled: true
    key-store: d:\ssl_certificates\server.jks
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost
eureka:
  instance:
    hostname: rixp330
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://rixp330:8061/eureka/, https://rixm1mini:8061/eureka/, https://rixmbp:8061/eureka/
logging:
  config: classpath:logback-local-p330-cluster.xml

---
spring:
  config:
    activate:
      on-profile: local-m1mac-single

server:
  ssl:
    enabled: true
    key-store: /Users/rixonmathew/local_ssl_certs/server.jks
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost

eureka:
  instance:
    hostname: rixm1mini
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://rixm1mini:8061/eureka/

---
spring:
  config:
    activate:
      on-profile: local-m1mac-cluster

server:
  ssl:
    enabled: true
    key-store: /Users/rixonmathew/local_ssl_certs/server.jks
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost

eureka:
  instance:
    hostname: rixm1mini
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://rixp330:8061/eureka/, https://rixm1mini:8061/eureka/, https://rixmbp:8061/eureka/

---
spring:
  config:
    activate:
      on-profile: local-mbp-single

server:
  ssl:
    enabled: true
    key-store: /Users/rixonmathew/local_ssl_certs/server.jks
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost

eureka:
  instance:
    hostname: rixmbp
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://rixmbp:8061/eureka/

---
spring:
  config:
    activate:
      on-profile: local-mbp-cluster

server:
  ssl:
    enabled: true
    key-store: /Users/rixonmathew/local_ssl_certs/server.jks
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost

eureka:
  instance:
    hostname: rixmbp
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://rixp330:8061/eureka/, https://rixm1mini:8061/eureka/, https://rixmbp:8061/eureka/
