server:
  port: 9797

spring:
  application:
    name: department-service-webmvc

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
info:
  name: Department Services Webmvc
  category: Red
logging:
  level:
    root: TRACE
