server:
  port: 9797

spring:
  application:
    name: healthcare-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
